export const webHindi: Record<string, string> = {
  "Settings": "सेटिंग्स",
  "Book": "बुक करें",
  "Name, Gender, DOB": "नाम, लिंग, जन्मतिथि",
  "View active and past orders": "चल रहे और पुराने ऑर्डर देखें",
  "Contact our support team": "हमारी सहायता टीम से बात करें",
  "Payments, Refunds & more": "भुगतान, रिफंड और अन्य जानकारी",
  "Login to": "लॉगिन करें",
  "Darji": "दर्जी",
  "Enter your mobile number to continue": "जारी रखने के लिए अपना मोबाइल नंबर दर्ज करें",
  "Enter the verification code sent to your phone": "आपके फोन पर भेजा गया ओटीपी दर्ज करें",
  "Mobile number": "मोबाइल नंबर",
  "Verification code": "ओटीपी",
  "Verify": "सत्यापित करें",
  "Change Phone": "नंबर बदलें",
  "or": "या",
  "and": "और",
  "We never share your number with anyone.": "हम आपका नंबर किसी के साथ साझा नहीं करते।",
  "By continuing, you agree to our": "जारी रखकर आप हमारी इन शर्तों से सहमत हैं:",
  "Terms & Conditions": "नियम और शर्तें",
  "Syncing": "अपडेट हो रहा है",
  "Syncing orders, wallet, coupons, addresses, and delivery verification data.": "ऑर्डर, वॉलेट, कूपन, पते और डिलीवरी की जानकारी अपडेट हो रही है।",
  "Order placed": "ऑर्डर हो गया",
  "Your order is confirmed. You can track pickup, delivery OTP, tailor status, and payment details from My Orders.": "आपका ऑर्डर कन्फर्म हो गया है। मेरे ऑर्डर में पिकअप, डिलीवरी ओटीपी, दर्जी और भुगतान की जानकारी देखें।",
  "Go to My Orders": "मेरे ऑर्डर देखें",
  "Doorstep Tailoring": "घर बैठे सिलाई सेवा",
  "Start with photos.": "फोटो से शुरुआत करें।",
  "Finish with a confirmed tailor.": "अपना दर्जी चुनें।",
  "Upload your clothes, tell us the issue and get quotes from trusted tailors near you.": "कपड़ों की फोटो डालें, काम बताएं और आसपास के विश्वसनीय दर्जियों से कोटेशन पाएं।",
  "Continue Booking": "बुकिंग जारी रखें",
  "Book a Service": "सेवा बुक करें",
  "View Orders": "ऑर्डर देखें",
  "Step": "चरण",
  "Live Orders •": "चल रहे ऑर्डर •",
  "Track your current orders": "अपने मौजूदा ऑर्डर ट्रैक करें",
  "See all orders": "सभी ऑर्डर देखें",
  "Start Booking": "बुकिंग शुरू करें",
  "What's the issue with your clothing?": "आपके कपड़ों में क्या काम करना है?",
  "Describe the issue or alteration you need.": "जरूरी काम या बदलाव के बारे में बताएं।",
  "Example: sleeves are loose, waist needs fitting, zip repair, or custom stitching details.": "जैसे: आस्तीन ढीली है, कमर की फिटिंग, जिप की मरम्मत या नई सिलाई।",
  "Where should we pick up your clothes?": "कपड़े कहां से लेने हैं?",
  "Use Current Location": "मौजूदा स्थान का इस्तेमाल करें",
  "Upload photos or videos": "फोटो या वीडियो अपलोड करें",
  "Remove media": "मीडिया हटाएं",
  "Uploading media...": "मीडिया अपलोड हो रहा है...",
  "Uploading media, then continuing...": "मीडिया अपलोड होते ही आगे बढ़ेंगे...",
  "Photos must be 5 MB or smaller.": "फोटो 5 MB या उससे छोटी होनी चाहिए।",
  "Videos must be 20 MB or smaller.": "वीडियो 20 MB या उससे छोटी होनी चाहिए।",
  "Up to 6 files • Photos 5 MB • Videos 20 MB": "अधिकतम 6 फाइलें • फोटो 5 MB • वीडियो 20 MB",
  "Help tailors understand the issue better.": "दर्जी को काम समझने में मदद करें।",
  "Back to Summary": "सारांश पर वापस जाएं",
  "Saved in this order": "इस ऑर्डर में जोड़ा गया",
  "clothing item": "कपड़ा",
  "s": "",
  "Work Type": "काम का प्रकार",
  "Work details": "काम का विवरण",
  "Select the work you need": "अपनी जरूरत का काम चुनें",
  "Select a measurement visit time slot": "नाप लेने की विजिट का समय चुनें",
  "Preferred visit time": "विजिट का पसंदीदा समय",
  "Select time slot": "समय चुनें",
  "View Cloth Requirement Guide": "कपड़े की जरूरत की गाइड देखें",
  "Our tailor will use an existing fit reference for accuracy.": "सही फिटिंग के लिए दर्जी आपके पुराने कपड़े का नमूना इस्तेमाल करेगा।",
  "Enter manually measurements?": "नाप खुद दर्ज करें?",
  "You can enter your measurements manually if you already have them.": "यदि आपके पास नाप है तो उसे यहां दर्ज कर सकते हैं।",
  "Manual Measurements (cm)": "खुद दर्ज किया गया नाप (सेमी)",
  "Fit preference, loose/tight notes, old garment reference, or special instructions.": "पसंदीदा फिटिंग, ढीला या टाइट, पुराने कपड़े का नमूना या खास निर्देश।",
  "Review Order": "ऑर्डर जांचें",
  "Cloth Requirement Guide": "कपड़े की जरूरत की गाइड",
  "Close Guide": "गाइड बंद करें",
  "Book service": "सेवा बुक करें",
  "guide": "गाइड",
  "Order summary": "ऑर्डर का सारांश",
  "Delivery Fee Calculation": "डिलीवरी शुल्क की गणना",
  "km": "किमी",
  "Round Trip": "आना-जाना",
  "Base Fare (": "मूल किराया (",
  "Distance (": "दूरी (",
  "/km)": "/किमी)",
  "Breakdown Total": "कुल शुल्क",
  "Calculated from customer location to tailor shop address. Covers 2-way doorstep pickup and drop.": "ग्राहक के स्थान से दर्जी की दुकान तक की दूरी के अनुसार। इसमें घर से पिकअप और वापस डिलीवरी शामिल है।",
  "Add one cloth before requesting quotes.": "कोटेशन मांगने से पहले एक कपड़ा जोड़ें।",
  "Get Quotes": "कोटेशन पाएं",
  "Home Visit": "घर पर विजिट",
  "Checking tailor quotes": "दर्जियों के कोटेशन देख रहे हैं",
  "Your request is open. Quotes will appear here when verified tailors respond.": "आपका अनुरोध भेज दिया गया है। सत्यापित दर्जियों के कोटेशन यहां दिखेंगे।",
  "Confirm This Tailor": "इस दर्जी को चुनें",
  "Your payment is safe and secure with us.": "आपका भुगतान सुरक्षित है।",
  "Not rated yet": "अभी रेटिंग नहीं है",
  "Extra": "अतिरिक्त",
  "Included": "शामिल",
  "Selected tailor": "चुना गया दर्जी",
  "• Verified": "• सत्यापित",
  "Cards, Netbanking, Wallets": "कार्ड, नेट बैंकिंग, वॉलेट",
  "Coupons & Offers": "कूपन और ऑफर",
  "applied": "लागू",
  "Payment Summary": "भुगतान का सारांश",
  "Total (incl. taxes)": "कुल (कर सहित)",
  "Pay": "भुगतान करें",
  "100% Secure Payments": "पूरी तरह सुरक्षित भुगतान",
  "Items in this order": "इस ऑर्डर के कपड़े",
  "Verified Tailors": "सत्यापित दर्जी",
  "Background checked": "जांच की गई है",
  "On-time Delivery": "समय पर डिलीवरी",
  "Always on schedule": "तय समय के अनुसार",
  "Secure Payments": "सुरक्षित भुगतान",
  "100% safe & secure": "पूरी तरह सुरक्षित",
  "Satisfaction Guarantee": "संतुष्टि का भरोसा",
  "Love it or we'll fix it": "दिक्कत हो तो हमें बताएं",
  "Verifying Payment": "भुगतान की जांच हो रही है",
  "We are fetching your payment status. Please do not refresh the page or click back.": "भुगतान की स्थिति जांच रहे हैं। पेज रिफ्रेश न करें और वापस न जाएं।",
  "Track and manage all your tailoring orders in one place.": "सिलाई के सभी ऑर्डर एक जगह देखें और संभालें।",
  "Waiting for Pickup": "पिकअप का इंतजार",
  "Filter": "फ़िल्टर",
  "Sort Latest": "नए पहले",
  "Sort Oldest": "पुराने पहले",
  "Try another filter or create a new booking.": "दूसरा फ़िल्टर चुनें या नई बुकिंग करें।",
  "Need Help with your order?": "ऑर्डर के बारे में मदद चाहिए?",
  "Our support team is here to help you.": "हमारी सहायता टीम आपकी मदद के लिए है।",
  "Chat with us": "हमसे चैट करें",
  "New Order": "नया ऑर्डर",
  "Book your first pickup and confirmed tailoring orders will appear here.": "पहला पिकअप बुक करें। कन्फर्म सिलाई ऑर्डर यहां दिखेंगे।",
  "Clothing Item": "कपड़ा",
  "ETA:": "अनुमानित समय:",
  "Wear -": "कपड़े -",
  "Delivery:": "डिलीवरी:",
  "Pickup Partner Assigned": "पिकअप पार्टनर नियुक्त",
  "Quote pending": "कोटेशन का इंतजार",
  "Rate your experience": "अपने अनुभव को रेट करें",
  "Loading delivery OTP": "डिलीवरी ओटीपी लोड हो रहा है",
  "Delivery OTP": "डिलीवरी ओटीपी",
  "Verified by delivery partner.": "डिलीवरी पार्टनर ने सत्यापित किया।",
  "Share this only when the delivery partner reaches you.": "डिलीवरी पार्टनर के पहुंचने पर ही इसे साझा करें।",
  "Pickup verification": "पिकअप सत्यापन",
  "Drop verification": "डिलीवरी सत्यापन",
  "Checkout": "चेकआउट",
  "Continue this order": "यह ऑर्डर जारी रखें",
  "Waiting for quotes": "कोटेशन का इंतजार",
  "Quotes for this request will appear here.": "इस अनुरोध के कोटेशन यहां दिखेंगे।",
  "Payable": "देय राशि",
  "Tap photo to change": "फोटो बदलने के लिए दबाएं",
  "Choose Avatar": "अवतार चुनें",
  "Add an address to make your doorstep booking seamless.": "घर से पिकअप बुक करने के लिए पता जोड़ें।",
  "Available Balance": "उपलब्ध राशि",
  "Use this balance for quick checkout on your tailoring requests.": "अपने सिलाई अनुरोधों के भुगतान के लिए यह राशि इस्तेमाल करें।",
  "Your wallet transactions will be listed here.": "आपके वॉलेट के लेनदेन यहां दिखेंगे।",
  "Orders & Wallet": "ऑर्डर और वॉलेट",
  "Legal & App": "कानूनी जानकारी और ऐप",
  "Resolve": "समाधान हो गया",
  "No messages yet.": "अभी कोई संदेश नहीं है।",
  "No messages yet": "अभी कोई संदेश नहीं है",
  "Type your first message below to open this support ticket.": "सहायता टिकट खोलने के लिए पहला संदेश नीचे लिखें।",
  "General Query (No Order)": "सामान्य सवाल (कोई ऑर्डर नहीं)",
  "Attach Image Reference (Optional)": "फोटो जोड़ें (वैकल्पिक)",
  "Add Photo": "फोटो जोड़ें",
  "Bug Title": "समस्या का शीर्षक",
  "e.g. App crashes when selecting payment": "जैसे: भुगतान चुनते समय ऐप बंद हो जाता है",
  "Describe the issue you encountered and the steps to reproduce it.": "समस्या और उसके होने से पहले किए गए चरण बताएं।",
  "Attach Screenshot reference (Optional)": "स्क्रीनशॉट जोड़ें (वैकल्पिक)",
  "OPEN TICKETS (": "खुले टिकट (",
  "RESOLVED TICKETS (": "हल किए गए टिकट (",
  "Resolved": "हल हो गया",
  "BUG REPORTS (": "समस्या रिपोर्ट (",
  "Saved addresses": "सेव किए गए पते",
  "No saved addresses yet.": "अभी कोई पता सेव नहीं है।",
  "No coupons available.": "अभी कोई कूपन उपलब्ध नहीं है।",
  "No notifications yet.": "अभी कोई सूचना नहीं है।",
  "Wallet activity": "वॉलेट के लेनदेन",
  "No wallet transactions yet.": "अभी कोई वॉलेट लेनदेन नहीं है।",
  "Order ID, issue, or request": "ऑर्डर आईडी, समस्या या अनुरोध",
  "Support request sent.": "सहायता अनुरोध भेज दिया गया।",
  "Send Support Request": "सहायता अनुरोध भेजें",
  "Nothing here yet": "अभी यहां कुछ नहीं है",
  "Search tailors": "दर्जी खोजें",
  "Save tailor": "दर्जी सेव करें",
  "Book Pickup": "पिकअप बुक करें",
  "Check payment status": "भुगतान की स्थिति जांचें",
  "Cancellation reason": "रद्द करने का कारण",
  "Cancel order": "ऑर्डर रद्द करें",
  "Reschedule delivery": "डिलीवरी का समय बदलें",
  "Time pending": "समय तय होना बाकी है",
  "Select order": "ऑर्डर चुनें",
  "Your review": "आपका रिव्यू",
  "Submit review": "रिव्यू भेजें",
  "Thank you for your review": "आपके रिव्यू के लिए धन्यवाद",
  "Measurement guide": "नाप की गाइड",
  "Measurements in inches": "नाप इंच में",
  "Cancellation policy": "रद्द करने की नीति",
  "Voice notes": "वॉइस नोट",
  "Upload audio": "ऑडियो अपलोड करें",
  "Remove voice note": "वॉइस नोट हटाएं",
  "Record": "रिकॉर्ड करें",
  "Stop recording": "रिकॉर्डिंग बंद करें",
  "Add up to 3 voice notes, 10 MB each": "अधिकतम 3 वॉइस नोट जोड़ें, हर नोट 10 एमबी तक",
  "Recording is unavailable. Upload an audio file instead.": "रिकॉर्डिंग उपलब्ध नहीं है। ऑडियो फाइल अपलोड करें।",
  "Find Tailors": "दर्जी खोजें",
  "App language": "ऐप की भाषा",
  "Notification preferences": "सूचना की पसंद",
  "Customer stories": "ग्राहकों के अनुभव",
  "Payment status": "भुगतान की स्थिति",
  "Payment received": "भुगतान मिल गया",
  "Payment is pending": "भुगतान बाकी है",
  "Cancellation charges may apply after pickup. Continue?": "पिकअप के बाद रद्द करने का शुल्क लग सकता है। जारी रखें?",
  "Are you sure you want to log out?": "क्या आप लॉग आउट करना चाहते हैं?",
  "Normal (up to 7 days)": "सामान्य (7 दिन तक)",
  "Express (3-5 days)": "एक्सप्रेस (3-5 दिन)",
  "Awaiting quotes": "कोटेशन का इंतजार",
  "Payment pending": "भुगतान बाकी है"
};
