// Reviewed static customer copy; no runtime translation requests.
export const customerHindi: Record<string, string> = {
  "Why Choose Darji?": "दर्जी क्यों चुनें?",
  "Doorstep Service": "घर तक सेवा",
  "Pickup and delivery": "पिकअप और डिलीवरी",
  "Trusted Tailors": "भरोसेमंद दर्जी",
  "Verified partners": "सत्यापित साथी",
  "Best Prices": "बेहतरीन कीमतें",
  "Compare Pricing": "कीमतों की तुलना करें",
  "Secure & Safe": "सुरक्षित सेवा",
  "Protected orders": "सुरक्षित ऑर्डर",
  "How pickup works": "पिकअप कैसे होता है",
  "Schedule a slot and our partner collects your garment.": "समय चुनें और हमारा साथी आपके कपड़े लेने आएगा।",
  "Choose pickup address and preferred service while creating a request.": "अनुरोध बनाते समय पिकअप का पता और सेवा चुनें।",
  "Darji assigns a pickup partner and shares live status updates.": "दर्जी पिकअप साथी नियुक्त करता है और ताज़ा स्थिति बताता है।",
  "Keep clothes packed and ready. The partner verifies the request before handover.": "कपड़े पैक करके तैयार रखें। साथी कपड़े लेने से पहले अनुरोध की जाँच करेगा।",
  "After pickup, your garment is delivered to the selected tailor.": "पिकअप के बाद कपड़े चुने हुए दर्जी तक पहुँचाए जाते हैं।",
  "How quotes work": "कीमत के प्रस्ताव कैसे मिलते हैं",
  "Tailors respond after reviewing uploaded photos.": "दर्जी अपलोड की गई तस्वीरें देखकर प्रस्ताव भेजते हैं।",
  "Upload clear cloth photos and describe the work needed.": "कपड़ों की साफ़ तस्वीरें अपलोड करें और ज़रूरी काम बताएँ।",
  "Nearby tailors review the request and submit price and timeline.": "आसपास के दर्जी अनुरोध देखकर कीमत और समय बताते हैं।",
  "Compare quotes, ratings, and expected completion time.": "कीमतों, रेटिंग और काम पूरा होने के समय की तुलना करें।",
  "Select one quote to confirm and move to payment.": "पुष्टि और भुगतान के लिए एक प्रस्ताव चुनें।",
  "How delivery works": "डिलीवरी कैसे होती है",
  "We deliver your stitched order back to your doorstep.": "हम सिले हुए कपड़े आपके घर पहुँचाते हैं।",
  "Darji tracks pickup, tailor handover, stitching, and final delivery.": "दर्जी पिकअप, दर्जी को सौंपने, सिलाई और डिलीवरी की स्थिति बताता है।",
  "You receive status updates when the order is dispatched.": "ऑर्डर भेजे जाने पर आपको सूचना मिलती है।",
  "Delivery OTP may be used to complete secure handover.": "सुरक्षित डिलीवरी के लिए ओटीपी माँगा जा सकता है।",
  "Report any delivery issue from Contact Support.": "डिलीवरी की समस्या के लिए सहायता से संपर्क करें।",
  "Payments and refunds": "भुगतान और धनवापसी",
  "UPI, cards and cash on delivery are supported.": "यूपीआई, कार्ड और डिलीवरी पर नकद भुगतान उपलब्ध हैं।",
  "You can pay online through Razorpay or use COD when available.": "रेज़रपे से ऑनलाइन या जहाँ उपलब्ध हो वहाँ डिलीवरी पर नकद भुगतान करें।",
  "Refunds follow the cancellation policy for the order status.": "धनवापसी ऑर्डर की स्थिति के अनुसार रद्दीकरण नीति के तहत होती है।",
  "Failed online payments can be retried from the order screen.": "ऑर्डर स्क्रीन से असफल ऑनलाइन भुगतान फिर कर सकते हैं।",
  "Payment support can help with duplicate debit or refund delays.": "दो बार पैसे कटने या धनवापसी में देरी पर भुगतान सहायता से संपर्क करें।",
  "Pricing and charges": "कीमत और शुल्क",
  "Understand pricing, additional charges and payment details.": "कीमत, अतिरिक्त शुल्क और भुगतान का विवरण जानें।",
  "Tailors set the stitching or alteration quote after reviewing your request.": "दर्जी आपका अनुरोध देखकर सिलाई या बदलाव की कीमत तय करते हैं।",
  "Darji may add delivery, platform, small-order, or home-measurement fees.": "दर्जी डिलीवरी, प्लेटफ़ॉर्म, छोटे ऑर्डर या घर पर नाप लेने का शुल्क जोड़ सकता है।",
  "The final amount is shown before you confirm payment.": "भुगतान की पुष्टि से पहले कुल राशि दिखाई जाती है।",
  "Any cancellation charges are shown in the cancellation policy.": "रद्दीकरण शुल्क रद्दीकरण नीति में दिए गए हैं।",
  "My account": "मेरा खाता",
  "Update profile, addresses and manage your account.": "प्रोफ़ाइल और पते बदलें तथा अपना खाता सँभालें।",
  "Edit your name, gender, date of birth, and avatar from Profile.": "प्रोफ़ाइल में नाम, लिंग, जन्मतिथि और तस्वीर बदलें।",
  "Saved addresses can be added, deleted, or selected during requests.": "अनुरोध करते समय सहेजे गए पते जोड़ें, हटाएँ या चुनें।",
  "Language and notification settings are separated under Preferences.": "पसंद अनुभाग में भाषा और सूचनाओं की अलग सेटिंग हैं।",
  "Account deletion permanently clears the local profile data from this device.": "खाता हटाने से इस डिवाइस पर सहेजा गया प्रोफ़ाइल डेटा हमेशा के लिए मिट जाता है।",
  "My orders": "मेरे ऑर्डर",
  "Track your order status and view order details.": "ऑर्डर की स्थिति और विवरण देखें।",
  "Open Orders to see active, pending, delivered, and cancelled requests.": "चल रहे, लंबित, पहुँचाए गए और रद्द अनुरोध देखने के लिए ऑर्डर खोलें।",
  "Track Order shows pickup, tailor handover, stitching, and delivery progress.": "ऑर्डर ट्रैकिंग में पिकअप, दर्जी को सौंपने, सिलाई और डिलीवरी की प्रगति देखें।",
  "Incomplete requests can be resumed from Orders.": "अधूरे अनुरोध ऑर्डर अनुभाग से आगे बढ़ा सकते हैं।",
  "Invoices are available after eligible delivered orders.": "योग्य ऑर्डर की डिलीवरी के बाद बिल उपलब्ध होता है।",
  "How does pickup work?": "पिकअप कैसे होता है?",
  "Schedule a slot and our partner will pick up your clothes from your address.": "समय चुनें और हमारा साथी आपके पते से कपड़े ले जाएगा।",
  "How long does stitching take?": "सिलाई में कितना समय लगता है?",
  "It usually takes 2-5 days depending on the service, fabric work, tailor availability, and delivery distance.": "सेवा, कपड़े के काम, दर्जी की उपलब्धता और दूरी के अनुसार आम तौर पर २–५ दिन लगते हैं।",
  "How do I get pricing?": "कीमत कैसे पता चलेगी?",
  "Upload your requirements and you will receive quotes from verified tailors before confirming the order.": "अपनी ज़रूरतें अपलोड करें। ऑर्डर की पुष्टि से पहले सत्यापित दर्जियों से कीमत के प्रस्ताव मिलेंगे।",
  "What payment methods are available?": "भुगतान के कौन से तरीके उपलब्ध हैं?",
  "We support UPI, cards, online payment options, and cash on delivery where available.": "यूपीआई, कार्ड, ऑनलाइन भुगतान और जहाँ उपलब्ध हो वहाँ डिलीवरी पर नकद भुगतान स्वीकार हैं।",
  "Can I track my order?": "क्या मैं अपना ऑर्डर ट्रैक कर सकता हूँ?",
  "Yes. You can track pickup, stitching, and delivery from the order tracking screen.": "हाँ। ऑर्डर ट्रैकिंग स्क्रीन से पिकअप, सिलाई और डिलीवरी की स्थिति देख सकते हैं।",
  "What if I am not satisfied with the order?": "ऑर्डर से संतुष्ट न होने पर क्या करूँ?",
  "Contact support from the order or help section. We will help with a resolution.": "ऑर्डर या सहायता अनुभाग से संपर्क करें। हम समस्या सुलझाने में मदद करेंगे।",
  "Order cancellation": "ऑर्डर रद्द करना",
  "Cancellation is free before pickup. After pickup, delivery charges and cancellation fee may apply. After tailor handover, cancellation is not allowed.": "पिकअप से पहले रद्द करना मुफ़्त है। पिकअप के बाद डिलीवरी और रद्दीकरण शुल्क लग सकते हैं। दर्जी को कपड़े सौंपने के बाद रद्द करना संभव नहीं है।",
  "Before Pickup": "पिकअप से पहले",
  "Awaiting payment, confirmed, or pickup not started": "भुगतान की प्रतीक्षा, पुष्टि हो चुकी या पिकअप शुरू नहीं हुआ",
  "Allowed": "अनुमति है",
  "100% refund": "१००% धनवापसी",
  "No cancellation charges": "कोई रद्दीकरण शुल्क नहीं",
  "If the package has not been picked up from your home, cancellation is free.": "यदि आपके घर से कपड़े नहीं उठाए गए हैं, तो रद्द करना मुफ़्त है।",
  "After Pickup, Before Tailor Handover": "पिकअप के बाद, दर्जी को सौंपने से पहले",
  "Pickup started or clothes collected from customer": "पिकअप शुरू या ग्राहक से कपड़े ले लिए गए",
  "Order refund after deducting charges": "शुल्क काटकर ऑर्डर की धनवापसी",
  "Delivery charge + cancellation fee": "डिलीवरी शुल्क + रद्दीकरण शुल्क",
  "Once the rider has picked up the package, transport and handling charges apply even if tailoring has not started.": "साथी के कपड़े लेने के बाद परिवहन और रखरखाव शुल्क लगते हैं, भले ही सिलाई शुरू न हुई हो।",
  "After Tailor Handover": "दर्जी को सौंपने के बाद",
  "Delivered to tailor, stitching started, ready, or out for delivery": "दर्जी को सौंपा गया, सिलाई शुरू, तैयार या डिलीवरी के लिए निकला",
  "Not allowed": "अनुमति नहीं है",
  "No refund": "धनवापसी नहीं",
  "Full order amount may be charged": "ऑर्डर की पूरी राशि ली जा सकती है",
  "Once the package is handed over to the tailor, the order is locked and cannot be cancelled.": "दर्जी को कपड़े सौंपने के बाद ऑर्डर रद्द नहीं किया जा सकता।",
  "Tailor unable to complete the order": "दर्जी ऑर्डर पूरा करने में असमर्थ",
  "Customer receives a full refund.": "ग्राहक को पूरी राशि वापस मिलेगी।",
  "Cloth damaged by Darji or tailor": "दर्जी सेवा या सिलाई करने वाले से कपड़ा क्षतिग्रस्त",
  "Customer may receive a full refund or compensation according to company policy.": "कंपनी की नीति के अनुसार पूरी धनवापसी या मुआवज़ा मिल सकता है।",
  "Delay beyond promised delivery date": "तय डिलीवरी तारीख से अधिक देरी",
  "Darji may provide a partial refund, discount coupon, or free express delivery.": "दर्जी आंशिक धनवापसी, छूट कूपन या मुफ़्त तेज़ डिलीवरी दे सकता है।",
  "Darji Cancellation Policy": "दर्जी रद्दीकरण नीति",
  "Cancellation is free before pickup. After pickup, delivery charges and a cancellation fee apply until the package reaches the tailor.": "पिकअप से पहले रद्द करना मुफ़्त है। पिकअप के बाद, दर्जी तक कपड़े पहुँचने से पहले रद्द करने पर डिलीवरी और रद्दीकरण शुल्क लगते हैं।",
  "SELECTED ORDER": "चुना गया ऑर्डर",
  "Order Status": "ऑर्डर की स्थिति",
  "Refund": "धनवापसी",
  "Charges": "शुल्क",
  "SPECIAL CASES": "विशेष परिस्थितियाँ",
  "Keep Order": "ऑर्डर जारी रखें",
  "Cancelling Order...": "ऑर्डर रद्द हो रहा है...",
  "I Understand, Cancel Order": "मैं समझता हूँ, ऑर्डर रद्द करें",
  "Cancellation Not Allowed": "ऑर्डर रद्द नहीं किया जा सकता",
  "PRIVACY & DATA": "गोपनीयता और डेटा",
  "TERMS": "शर्तें",
  "Darji uses your phone number for login, uploaded media to prepare tailoring quotes, and location/address details for pickup and delivery. You can edit profile details and control app permissions from Settings.": "दर्जी लॉगिन के लिए फ़ोन नंबर, सिलाई के प्रस्ताव के लिए अपलोड की गई सामग्री और पिकअप व डिलीवरी के लिए स्थान तथा पते का उपयोग करता है। सेटिंग से प्रोफ़ाइल और ऐप की अनुमतियाँ बदल सकते हैं।",
  "By using Darji, you agree to provide accurate request details, confirm pickup addresses, and pay for confirmed orders. Tailor quotes and delivery timelines may vary based on garment condition and service availability.": "दर्जी का उपयोग करके आप अनुरोध का सही विवरण देने, पिकअप पते की पुष्टि करने और पक्के ऑर्डर का भुगतान करने के लिए सहमत होते हैं। कपड़ों की स्थिति और सेवा की उपलब्धता के अनुसार कीमत और डिलीवरी का समय बदल सकता है।",
  "Open Privacy Policy": "गोपनीयता नीति खोलें",
  "Open Terms of Service": "सेवा की शर्तें खोलें",
  "GET STARTED": "शुरुआत करें",
  "PAYMENTS": "भुगतान",
  "ACCOUNT & ORDERS": "खाता और ऑर्डर",
  "POLICIES & INFORMATION": "नीतियाँ और जानकारी"
};
