// Human-reviewed UI copy shared by the three mobile apps. Never translate user data here.
export const reviewedHindiUi: Record<string, string> = {
  "Choose Delivery Timing": "डिलीवरी का समय चुनें",
  "This timing applies to every clothing item in this order.": "यह समय इस ऑर्डर के हर कपड़े पर लागू होगा।",
  "We are having trouble connecting right now. Check your internet connection and try again.": "अभी कनेक्ट करने में परेशानी हो रही है। अपना इंटरनेट कनेक्शन जाँचें और दोबारा कोशिश करें।",
  "This is taking longer than expected. Check your internet connection and try again.": "इसमें उम्मीद से अधिक समय लग रहा है। अपना इंटरनेट कनेक्शन जाँचें और दोबारा कोशिश करें।",
  "We are having some trouble right now. Please try again in a moment.": "अभी कुछ परेशानी हो रही है। कृपया थोड़ी देर बाद दोबारा कोशिश करें।",
  "Something went wrong. Please try again.": "कुछ गलत हो गया। कृपया दोबारा कोशिश करें।",
  "We could not check your account right now. Please try again.": "अभी आपका खाता जाँचा नहीं जा सका। कृपया दोबारा कोशिश करें।",
  "We could not check your account right now. Your saved login has not been changed.": "अभी आपका खाता जाँचा नहीं जा सका। आपका सेव किया हुआ लॉगिन बदला नहीं गया है।",
  "Partially synced": "कुछ जानकारी अपडेट नहीं हुई",
  "Complete admin verification first": "पहले एडमिन से अपने खाते का सत्यापन पूरा कराएँ।",
  "Quote": "कीमत का प्रस्ताव",
  "Quotes": "कीमत के प्रस्ताव",
  "Add at least one clothing item before requesting quotes.": "कीमत के प्रस्ताव माँगने से पहले कम से कम एक कपड़ा जोड़ें।",
  "Go online before sending quotes": "कीमत का प्रस्ताव भेजने से पहले ऑनलाइन जाएँ",
  "No quote is reserved for this request": "इस अनुरोध के लिए कोई कीमत का प्रस्ताव आरक्षित नहीं है",
  "This request is not accepting quotes": "यह अनुरोध अभी कीमत के प्रस्ताव स्वीकार नहीं कर रहा है",
  "Review every garment included in this quote before accepting it.": "कीमत का प्रस्ताव स्वीकार करने से पहले उसमें शामिल हर कपड़े का विवरण जाँचें।",
  "Delivery type changed after this quote was submitted. Please request fresh quotes.": "कीमत का प्रस्ताव मिलने के बाद डिलीवरी का प्रकार बदल गया। कृपया नए कीमत प्रस्ताव माँगें।",
  "Your review helps us reward great work and make every pickup, quote, and delivery feel better.": "आपका रिव्यू अच्छे काम को पहचानने और पिकअप, कीमत के प्रस्ताव तथा डिलीवरी की सेवा बेहतर बनाने में मदद करता है।",
  "Allow notifications so urgent requests can ring, vibrate, and show a popup.": "सूचनाओं की अनुमति दें ताकि ज़रूरी अनुरोधों पर घंटी बजे, फ़ोन वाइब्रेट करे और पॉपअप दिखे।",
  "Allow display over other apps to accept, reject, or view a waiting request from any screen.": "किसी भी स्क्रीन से लंबित अनुरोध स्वीकार करने, मना करने या देखने के लिए दूसरे ऐप के ऊपर दिखाने की अनुमति दें।",
  "Approve app notifications. If no popup appears, notification settings will open.": "ऐप की सूचनाओं को अनुमति दें। पॉपअप न दिखे तो सूचनाओं की सेटिंग खुलेगी।",
  "Allow full-screen alerts for this app.": "इस ऐप के लिए फ़ुल स्क्रीन अलर्ट की अनुमति दें।",
  "Rate Darji": "दर्जी को रेटिंग दें",
  "Receive & Rate": "कपड़े पाएँ और रेटिंग दें",
  "reviews": "रिव्यू",
  "reviews)": "रिव्यू)",
  "Price": "कीमत",
  "Interest rate": "ब्याज दर",
  "Rate": "रेट करें",
  "Rate & Review": "रेटिंग और रिव्यू दें",
  "Rate Darji app": "दर्जी ऐप को रेट करें",
  "Rate your tailor": "अपने दर्जी को रेटिंग दें",
  "Rate your delivery partner": "अपने डिलीवरी पार्टनर को रेटिंग दें",
  "Rating": "रेटिंग",
  "Ratings": "रेटिंग",
  "Review": "रिव्यू",
  "Reviews": "रिव्यू",
  "Submit Review": "रिव्यू भेजें",
  "Customer Reviews": "ग्राहकों के रिव्यू",
  "Rating must be 1-5": "रेटिंग १ से ५ के बीच होनी चाहिए",
  "Review already submitted": "रिव्यू पहले ही भेजा जा चुका है",
  "Review not found": "रिव्यू नहीं मिला",
  "Reviews can be submitted after delivery": "डिलीवरी के बाद रिव्यू दे सकते हैं",
  "Review the tailor and delivery partner separately.": "दर्जी और डिलीवरी पार्टनर को अलग-अलग रेटिंग और रिव्यू दें।",
  "You can only review your own orders": "आप केवल अपने ऑर्डर का रिव्यू दे सकते हैं",
  "We'll review and update it for you": "हम इसकी जाँच करके आपके लिए अपडेट करेंगे",
  "Compare Live Quotes": "नए कीमत प्रस्तावों की तुलना करें",
  "Use this guide before creating a request. Accurate measurements help tailors understand your fit and price the work correctly.": "अनुरोध बनाने से पहले यह गाइड देखें। सही नाप से दर्जी आपकी फिटिंग समझकर काम की सही कीमत बता पाएँगे।",
  "Darji is a modern tailoring ecosystem designed to bring custom clothing to your doorstep. We connect you with expert local tailors, facilitate live fabric and measurements collection, and ensure perfect-fit garments are delivered directly back to you.": "दर्जी सिलाई की सेवा आपके घर तक पहुँचाता है। हम आपको अनुभवी स्थानीय दर्जियों से जोड़ते हैं, कपड़ों के पिकअप और नाप लेने की व्यवस्था करते हैं और सही फिटिंग वाले कपड़े आपके घर पहुँचाते हैं।",
  "• Request a Quote: Share pictures and measurements.": "• कीमत का प्रस्ताव माँगें: तस्वीरें और नाप साझा करें।",
  "• Receive Quotes: Local tailors offer prices and timelines.": "• कीमत के प्रस्ताव पाएँ: स्थानीय दर्जी कीमत और समय बताते हैं।",
  "• Handoff: Receive your custom garment at your door.": "• कपड़े प्राप्त करें: तैयार कपड़े अपने घर पर लें।",
  "s": "सेकंड",
  "Tailoring": "सिलाई",
  "Paid": "भुगतान हो गया",
  "Weekly payout": "साप्ताहिक भुगतान",
  "0 MB": "० एमबी",
  "1 PM Batch": "दोपहर १ बजे का बैच",
  "6 PM Batch": "शाम ६ बजे का बैच",
  "Cloth": "कपड़ा",
  "Draft Conversation": "बातचीत का ड्राफ़्ट",
  "partner_rejected": "पार्टनर ने अस्वीकार किया",
  "Restart app": "ऐप दोबारा शुरू करें",
  "Retry update": "अपडेट फिर आज़माएँ",
  "All dates": "सभी तारीखें",
  "Allow locked-screen alerts": "लॉक स्क्रीन पर अलर्ट की अनुमति दें",
  "Allow notifications": "सूचनाओं की अनुमति दें",
  "Allow order popups": "ऑर्डर पॉपअप की अनुमति दें",
  "Allow request notifications": "अनुरोध की सूचनाओं की अनुमति दें",
  "Android 14 can limit full-screen alerts. This setting improves locked-screen request visibility while the overlay handles normal app and home-screen popups.": "एंड्रॉयड १४ फ़ुल स्क्रीन अलर्ट सीमित कर सकता है। यह सेटिंग लॉक स्क्रीन पर अनुरोध दिखाने में मदद करती है। ओवरले ऐप और होम स्क्रीन पर पॉपअप दिखाता है।",
  "Animated guide showing the App info menu and Allow restricted settings option": "ऐप की जानकारी और प्रतिबंधित सेटिंग की अनुमति देने का तरीका दिखाती एनिमेटेड गाइड",
  "Audio": "ऑडियो",
  "Create a request and get tailor quotes.": "अनुरोध बनाएँ और दर्जियों से कीमत के प्रस्ताव पाएँ।",
  "Darji tailoring offer": "दर्जी सिलाई ऑफ़र",
  "Date unavailable": "तारीख उपलब्ध नहीं",
  "Finding your location...": "आपका स्थान खोजा जा रहा है...",
  "ID pending": "आईडी लंबित",
  "Mark Collected From Tailor": "दर्जी से कपड़े ले लिए",
  "Mark Delivered": "डिलीवरी पूरी करें",
  "Mark Delivered To Tailor": "दर्जी को कपड़े सौंप दिए",
  "Mark Picked Up": "पिकअप पूरा करें",
  "Measurement visit": "नाप लेने की विज़िट",
  "New tailor": "नया दर्जी",
  "No active orders": "कोई चालू ऑर्डर नहीं",
  "No cancellation charge applies before pickup.": "पिकअप से पहले कोई रद्दीकरण शुल्क नहीं लगता।",
  "Offline": "ऑफ़लाइन",
  "Online": "ऑनलाइन",
  "Open App info": "ऐप की जानकारी खोलें",
  "Payment pending before confirmation": "पुष्टि से पहले भुगतान बाकी है",
  "Registered partner information": "पंजीकृत पार्टनर की जानकारी",
  "Request account deletion?": "खाता हटाने का अनुरोध भेजें?",
  "Review setting": "सेटिंग जाँचें",
  "Saving availability...": "उपलब्धता सेव हो रही है...",
  "Saving...": "सेव हो रहा है...",
  "Tailor Partner": "दर्जी पार्टनर",
  "Tap Allow notifications below.": "नीचे सूचनाओं की अनुमति देने वाला बटन दबाएँ।",
  "Tap Open App info below.": "नीचे ऐप की जानकारी खोलने वाला बटन दबाएँ।",
  "Tap Review setting below.": "नीचे सेटिंग जाँचने वाला बटन दबाएँ।",
  "Tap the three-dot menu and choose Allow restricted settings. If that option is absent, continue to the next step.": "तीन बिंदुओं वाला मेनू खोलकर प्रतिबंधित सेटिंग की अनुमति दें। विकल्प न मिले तो अगले चरण पर जाएँ।",
  "Use current location": "वर्तमान स्थान इस्तेमाल करें",
  "Verified by delivery partner": "डिलीवरी पार्टनर ने सत्यापित किया",
  "Verified partner information": "सत्यापित पार्टनर की जानकारी",
  "Waiting for tailor quotes": "दर्जियों के कीमत प्रस्तावों की प्रतीक्षा",
  "Yes, submit request": "हाँ, अनुरोध भेजें",
  "+ notes": "+ नोट्स",
  "12 hour deadline after accept": "स्वीकार करने के बाद १२ घंटे की समय सीमा",
  "A request becomes an assigned order only after the customer accepts your price. After that, it moves from Requests to Orders.": "ग्राहक के आपकी कीमत स्वीकार करने पर ही अनुरोध सौंपा गया ऑर्डर बनता है। इसके बाद वह अनुरोध से ऑर्डर अनुभाग में चला जाता है।",
  "A tailor will visit your home and take measurements accurately.": "दर्जी आपके घर आकर सही नाप लेगा।",
  "Accept home measurement visits when selected tailors decline.": "चुने हुए दर्जियों के मना करने पर घर जाकर नाप लेने की विज़िट स्वीकार करें।",
  "Accept only if you can start now": "अभी शुरू कर सकते हों तभी स्वीकार करें",
  "Accepted measurement visits will appear here.": "स्वीकार की गई नाप लेने की विज़िट यहाँ दिखेंगी।",
  "Active job": "चालू काम",
  "ACTIVE ORDER": "चालू ऑर्डर",
  "active request in this delivery": "इस डिलीवरी में चालू अनुरोध",
  "active requests in this delivery": "इस डिलीवरी में चालू अनुरोध",
  "Add Clip": "क्लिप जोड़ें",
  "Add or select your pickup address": "पिकअप का पता जोड़ें या चुनें",
  "Address not available": "पता उपलब्ध नहीं",
  "Aligning face...": "चेहरा सही जगह लाएँ...",
  "Alteration & Fitting": "अल्टरेशन और फिटिंग",
  "Applied": "लागू हो गया",
  "Assigned after confirmation": "पुष्टि के बाद नियुक्त होगा",
  "At checkout": "भुगतान के समय",
  "Available": "उपलब्ध",
  "Batch offered": "बैच का प्रस्ताव मिला",
  "Batch route active": "बैच का रूट चालू है",
  "Batches you have accepted and are ready to deliver.": "स्वीकार किए गए और डिलीवरी के लिए तैयार बैच।",
  "Blink detected, capturing...": "पलक झपकना पहचाना गया, तस्वीर ली जा रही है...",
  "Cancelled job": "रद्द किया गया काम",
  "Cancelled requests and orders.": "रद्द किए गए अनुरोध और ऑर्डर।",
  "Change Optional Sample Photo": "वैकल्पिक सैंपल तस्वीर बदलें",
  "Change Sample Photo": "सैंपल तस्वीर बदलें",
  "Checking phone location": "फ़ोन का स्थान जाँचा जा रहा है",
  "Checking quotes...": "कीमत के प्रस्ताव देखे जा रहे हैं...",
  "Cloth measurements": "कपड़े की नाप",
  "Complete Payment": "भुगतान पूरा करें",
  "Completed job": "पूरा हुआ काम",
  "Completion Time (Days)": "पूरा करने का समय (दिन)",
  "Completion Time (Hours)": "पूरा करने का समय (घंटे)",
  "Confirmations": "पुष्टियाँ",
  "Confirmed orders currently moving through pickup, tailoring, or delivery.": "पुष्टि किए गए ऑर्डर जिनका पिकअप, सिलाई या डिलीवरी चल रही है।",
  "Confirming payment": "भुगतान की पुष्टि हो रही है",
  "Connecting Directly": "सीधे संपर्क कराया जा रहा है",
  "Controls price requests and assignment visibility": "कीमत के अनुरोध और सौंपे गए काम दिखाने की सेटिंग",
  "Current location will be saved after login": "लॉगिन के बाद वर्तमान स्थान सेव होगा",
  "Customer recording": "ग्राहक की रिकॉर्डिंग",
  "Customer requests appear in the Requests tab when a customer asks for stitching, alteration, or tailoring work in your service area.": "आपके सेवा क्षेत्र में ग्राहक के सिलाई या अल्टरेशन का काम माँगने पर अनुरोध टैब में उसका अनुरोध दिखता है।",
  "Darji admin requested clearer documents. Open registration again and resubmit the details.": "दर्जी एडमिन ने अधिक साफ़ दस्तावेज़ माँगे हैं। पंजीकरण दोबारा खोलकर जानकारी जमा करें।",
  "Darji backend is not reachable right now. Your saved login has not been changed.": "अभी दर्जी सर्वर से संपर्क नहीं हो पा रहा। आपका सेव किया हुआ लॉगिन नहीं बदला है।",
  "Darji Collection": "दर्जी कलेक्शन",
  "Darji is verifying GPS access and securely updating your position.": "दर्जी जीपीएस की अनुमति जाँचकर आपका स्थान सुरक्षित रूप से अपडेट कर रहा है।",
  "Delivered orders and invoices.": "पहुँचाए गए ऑर्डर और बिल।",
  "Delivery partner requested account deletion from profile settings": "डिलीवरी पार्टनर ने प्रोफ़ाइल सेटिंग से खाता हटाने का अनुरोध किया",
  "Delivery partners must share precise phone GPS while using the app so dispatch can locate active riders and retain the last known position for safety.": "ऐप इस्तेमाल करते समय डिलीवरी पार्टनर को फ़ोन का सटीक जीपीएस स्थान साझा करना होगा, ताकि काम सौंपने वाली टीम सक्रिय पार्टनर को ढूँढ सके और सुरक्षा के लिए आख़िरी स्थान सहेज सके।",
  "Describe the work needed": "ज़रूरी काम बताएँ",
  "Description looks good.": "विवरण ठीक है।",
  "Direct instant delivery request. It is handled outside batch route optimization.": "सीधा तत्काल डिलीवरी अनुरोध। इसे बैच रूट की योजना से अलग सँभाला जाता है।",
  "Distance will be confirmed": "दूरी की पुष्टि की जाएगी",
  "Document reupload required": "दस्तावेज़ फिर अपलोड करने होंगे",
  "Draft request": "अनुरोध का ड्राफ़्ट",
  "DROP": "ड्रॉप",
  "Edit email": "ईमेल बदलें",
  "Embroidery & Custom Work": "कढ़ाई और कस्टम काम",
  "Embroidery, lace, patch work": "कढ़ाई, लेस और पैचवर्क",
  "Expired": "समय समाप्त",
  "Final delivery OTP": "अंतिम डिलीवरी ओटीपी",
  "Finishing Work": "फ़िनिशिंग का काम",
  "Full address will appear here as you fill the fields.": "जानकारी भरते समय पूरा पता यहाँ दिखेगा।",
  "Green circle: blink now": "हरा गोला: अब पलक झपकाएँ",
  "Handover package OTP": "पैकेज सौंपने का ओटीपी",
  "Hemming, pico, lining & more": "हेमिंग, पीको, अस्तर और अन्य काम",
  "Home measurement is mandatory for new stitching. You can also add a sample.": "नई सिलाई के लिए घर पर नाप लेना ज़रूरी है। आप सैंपल भी जोड़ सकते हैं।",
  "Home measurement request": "घर पर नाप लेने का अनुरोध",
  "house": "घर",
  "houses": "घर",
  "How Darji Works for Tailors": "दर्जियों के लिए दर्जी ऐप कैसे काम करता है",
  "INSTANT": "तत्काल",
  "Instant assigned": "तत्काल काम सौंपा गया",
  "INSTANT DELIVERY": "तत्काल डिलीवरी",
  "Instant offered": "तत्काल काम का प्रस्ताव",
  "item": "आइटम",
  "Just now": "अभी",
  "Locked": "लॉक है",
  "Mark an order as Ready when the garment is complete, checked, packed, and ready for pickup or delivery.": "कपड़ा पूरा होने, जाँच और पैकिंग के बाद, पिकअप या डिलीवरी के लिए तैयार होने पर ऑर्डर को तैयार चिह्नित करें।",
  "Measurement Visit Slot": "नाप लेने की विज़िट का समय",
  "Measurements & Timing": "नाप और समय",
  "Men": "पुरुष",
  "Navigate to the pickup point first.": "पहले पिकअप स्थान पर जाएँ।",
  "NEW DELIVERY": "नई डिलीवरी",
  "New home measurement offers will appear here.": "घर पर नाप लेने के नए प्रस्ताव यहाँ दिखेंगे।",
  "New pickup, delivery and cancellation requests": "नए पिकअप, डिलीवरी और रद्दीकरण अनुरोध",
  "New requests, accepted quotes and delivery handoff alerts": "नए अनुरोध, स्वीकार किए गए कीमत प्रस्ताव और डिलीवरी सौंपने के अलर्ट",
  "No accepted visits": "कोई स्वीकार की गई विज़िट नहीं",
  "No accepted visits scheduled yet": "अभी कोई स्वीकार की गई विज़िट तय नहीं है",
  "No history": "कोई हिस्ट्री नहीं",
  "No incoming visits": "कोई नई विज़िट नहीं",
  "No new requests yet": "अभी कोई नया अनुरोध नहीं",
  "No notes added by the customer.": "ग्राहक ने कोई नोट नहीं जोड़ा।",
  "No open requests": "कोई चालू अनुरोध नहीं",
  "No orders waiting in your work queue.": "आपके काम की सूची में कोई ऑर्डर बाकी नहीं है।",
  "No sent requests yet": "अभी कोई अनुरोध नहीं भेजा गया",
  "No written instructions added by the customer for this item.": "ग्राहक ने इस आइटम के लिए कोई लिखित निर्देश नहीं जोड़े।",
  "Not started": "शुरू नहीं हुआ",
  "Nothing here": "यहाँ कुछ नहीं है",
  "Open App Settings": "ऐप की सेटिंग खोलें",
  "Open pickup first": "पहले पिकअप खोलें",
  "Open task actions": "काम के विकल्प खोलें",
  "Optional, useful for detailed fitting instructions.": "वैकल्पिक, फिटिंग के विस्तृत निर्देशों के लिए उपयोगी।",
  "Order confirmations, tailoring updates, pickup and delivery alerts": "ऑर्डर की पुष्टि, सिलाई के अपडेट, पिकअप और डिलीवरी अलर्ट",
  "Orders that are stitched and ready for delivery pickup.": "सिलाई पूरी होने के बाद डिलीवरी पिकअप के लिए तैयार ऑर्डर।",
  "Orders you have accepted and are currently working on.": "स्वीकार किए गए ऑर्डर जिन पर आप काम कर रहे हैं।",
  "Owner admin access cannot be suspended or banned": "मुख्य एडमिन का एक्सेस निलंबित या बंद नहीं किया जा सकता",
  "Package delivered to tailor.": "कपड़े दर्जी को सौंप दिए गए।",
  "Paused": "रुका हुआ",
  "PENDING": "लंबित",
  "PICKUP": "पिकअप",
  "Pickup address not available": "पिकअप का पता उपलब्ध नहीं",
  "Pickup completed": "पिकअप पूरा हुआ",
  "Pickup is complete. Continue only to the drop point.": "पिकअप पूरा हो गया। अब केवल ड्रॉप स्थान पर जाएँ।",
  "Pickup not scheduled": "पिकअप का समय तय नहीं",
  "Pickup OTP": "पिकअप ओटीपी",
  "Pickup Slot": "पिकअप का समय",
  "Playing...": "चल रहा है...",
  "Prices you have sent to customers will appear here.": "ग्राहकों को भेजे गए कीमत प्रस्ताव यहाँ दिखेंगे।",
  "Reach the drop location": "ड्रॉप स्थान पर पहुँचें",
  "Reach the pickup location": "पिकअप स्थान पर पहुँचें",
  "Ready to replay": "दोबारा सुनने के लिए तैयार",
  "Receive package OTP": "पैकेज लेने का ओटीपी",
  "Record": "रिकॉर्ड करें",
  "Record a voice note": "वॉइस नोट रिकॉर्ड करें",
  "Recording paused": "रिकॉर्डिंग रुकी हुई है",
  "Recording...": "रिकॉर्डिंग जारी है...",
  "Remove screenshot": "स्क्रीनशॉट हटाएँ",
  "Repair & Mending": "मरम्मत और रफ़ू",
  "Repair tears, zips, buttons & more": "फटे कपड़े, ज़िप, बटन और अन्य मरम्मत",
  "request": "अनुरोध",
  "Request created": "अनुरोध बना",
  "requests": "अनुरोध",
  "Requests waiting for quotes or payment.": "कीमत के प्रस्ताव या भुगतान की प्रतीक्षा वाले अनुरोध।",
  "Required for new stitching so the fit is measured accurately.": "नई सिलाई में सही फिटिंग की नाप के लिए ज़रूरी।",
  "Reupload Documents": "दस्तावेज़ दोबारा अपलोड करें",
  "Rider will pick up the package from the customer.": "डिलीवरी पार्टनर ग्राहक से कपड़े लेगा।",
  "route": "रूट",
  "Route optimized from your current location.": "आपके वर्तमान स्थान से बेहतर रूट तय किया गया।",
  "Route will be optimized after acceptance.": "स्वीकार करने के बाद बेहतर रूट तय होगा।",
  "Safer than only typing measurements: one wrong number can affect the fit.": "केवल नाप लिखने से अधिक भरोसेमंद: एक ग़लत अंक फिटिंग बिगाड़ सकता है।",
  "Sample selected. Upload a photo so the tailor can check the reference.": "सैंपल चुना गया। दर्जी को संदर्भ दिखाने के लिए तस्वीर अपलोड करें।",
  "Save Failure": "सेव नहीं हुआ",
  "Searching for tailors...": "दर्जियों को खोजा जा रहा है...",
  "Select date": "तारीख चुनें",
  "Select date of birth": "जन्मतिथि चुनें",
  "Selected cloth": "चुना गया कपड़ा",
  "Selfie captured": "सेल्फ़ी ली गई",
  "Share only after checking the package and rider.": "पैकेज और डिलीवरी पार्टनर की जाँच के बाद ही साझा करें।",
  "Share only when the delivery partner reaches you.": "डिलीवरी पार्टनर के आपके पास पहुँचने पर ही साझा करें।",
  "Shown after selection": "चुनने के बाद दिखेगा",
  "Sleeve adjustment and fitting changes.": "आस्तीन और फिटिंग में बदलाव।",
  "Start a tailoring request and get quotes from nearby tailors.": "सिलाई का अनुरोध बनाएँ और आसपास के दर्जियों से कीमत के प्रस्ताव पाएँ।",
  "START HERE": "यहाँ से शुरू करें",
  "Stitch + Delivery": "सिलाई + डिलीवरी",
  "Stitch from fabric or design": "कपड़े या डिज़ाइन से सिलाई",
  "Submit bug report": "समस्या की रिपोर्ट भेजें",
  "Submitted and past measurement visits will appear here.": "जमा की गई और पिछली नाप लेने की विज़िट यहाँ दिखेंगी।",
  "Tailor account": "दर्जी का खाता",
  "Tailor availability": "दर्जी की उपलब्धता",
  "Tailor requested account deletion from profile settings": "दर्जी ने प्रोफ़ाइल सेटिंग से खाता हटाने का अनुरोध किया",
  "Tailoring order": "सिलाई का ऑर्डर",
  "Tailoring request": "सिलाई का अनुरोध",
  "Tap any clip to replay it, or add another short instruction.": "दोबारा सुनने के लिए क्लिप दबाएँ या एक और छोटा निर्देश जोड़ें।",
  "Thank you for joining Darji! Our team is verifying your details. You'll be notified once your account is approved.": "दर्जी से जुड़ने के लिए धन्यवाद! हमारी टीम आपकी जानकारी जाँच रही है। खाता मंज़ूर होने पर सूचना मिलेगी।",
  "The customer left a star rating without a written review.": "ग्राहक ने लिखित रिव्यू के बिना स्टार रेटिंग दी है।",
  "The selected time slot is unavailable.": "चुना गया समय उपलब्ध नहीं है।",
  "Tighten, loosen, adjust & more": "कसना, ढीला करना और अन्य बदलाव",
  "Turn on device location": "डिवाइस का स्थान चालू करें",
  "Two-way delivery": "दोनों तरफ़ की डिलीवरी",
  "Unavailable": "उपलब्ध नहीं",
  "Unisex / Uniform / Other": "सभी के लिए / यूनिफ़ॉर्म / अन्य",
  "Upcoming": "आने वाली",
  "Upload Sample Photo": "सैंपल की तस्वीर अपलोड करें",
  "Use Support Center when you need help with orders, account changes, payouts, bugs, or general app questions.": "ऑर्डर, खाते में बदलाव, भुगतान, समस्याओं या ऐप से जुड़े सवालों के लिए सहायता केंद्र जाएँ।",
  "Verification in Progress": "सत्यापन जारी है",
  "Verified shop details are protected, so changes are sent for review instead of changing instantly.": "सत्यापित दुकान की जानकारी सुरक्षित है, इसलिए बदलाव सीधे लागू होने के बजाय जाँच के लिए भेजे जाते हैं।",
  "Verify Delivery OTP": "डिलीवरी ओटीपी सत्यापित करें",
  "Verify delivery OTP and handoff proof": "डिलीवरी ओटीपी और सौंपने का प्रमाण जाँचें",
  "Verify Pickup OTP": "पिकअप ओटीपी सत्यापित करें",
  "Verify pickup OTP and photo proof": "पिकअप ओटीपी और तस्वीर का प्रमाण जाँचें",
  "Verify Tailor Handover OTP": "दर्जी से कपड़े लेने का ओटीपी सत्यापित करें",
  "Verify Tailor Receive OTP": "दर्जी को कपड़े देने का ओटीपी सत्यापित करें",
  "View cancelled delivery batches and the reason.": "रद्द डिलीवरी बैच और कारण देखें।",
  "View cancelled orders and the reasons.": "रद्द ऑर्डर और कारण देखें।",
  "View delivery partner details": "डिलीवरी पार्टनर की जानकारी देखें",
  "View new delivery batches waiting for your response.": "आपके जवाब की प्रतीक्षा वाले नए डिलीवरी बैच देखें।",
  "View phone details": "फ़ोन की जानकारी देखें",
  "View registered address": "पंजीकृत पता देखें",
  "View tailor profile details": "दर्जी की प्रोफ़ाइल देखें",
  "View your completed delivery batches and details.": "अपने पूरे हुए डिलीवरी बैच और विवरण देखें।",
  "View your completed orders and transaction history.": "अपने पूरे हुए ऑर्डर और लेनदेन की हिस्ट्री देखें।",
  "Waiting for batch": "बैच की प्रतीक्षा",
  "Watch the complete tutorial before submitting your verification.": "सत्यापन जमा करने से पहले पूरा ट्यूटोरियल देखें।",
  "We noticed you didn't get any tailor quotes, so we are connecting you with a tailor directly shortly. Hang tight!": "आपको कोई कीमत का प्रस्ताव नहीं मिला है। हम जल्द ही आपको सीधे दर्जी से जोड़ रहे हैं। थोड़ा इंतज़ार करें!",
  "We're finding the best tailors near you. New quotes will appear here automatically.": "हम आपके आसपास बेहतरीन दर्जी खोज रहे हैं। नए कीमत प्रस्ताव यहाँ अपने आप दिखेंगे।",
  "When customers send tailoring requests, they will show up here.": "ग्राहकों के सिलाई अनुरोध यहाँ दिखेंगे।",
  "Why delivery charge may differ": "डिलीवरी शुल्क अलग क्यों हो सकता है",
  "Women": "महिलाएँ",
  "You can select one or both options": "आप एक या दोनों विकल्प चुन सकते हैं",
  "You will be signed out of your Darji account on this device.": "इस डिवाइस पर आपके दर्जी खाते से लॉगआउट हो जाएगा।",
  "Your details stay private & safe with Darji.": "आपकी जानकारी दर्जी के साथ निजी और सुरक्षित रहती है।",
  "Your earnings are tracked in the Earnings screen. Eligible completed work is added to your wallet and paid out according to Darji payout rules.": "आपकी कमाई, कमाई स्क्रीन पर दर्ज होती है। योग्य पूरे हुए काम की राशि वॉलेट में जुड़ती है और दर्जी के भुगतान नियमों के अनुसार मिलती है।",
  "Your request will be sent to admin. Your account remains active until it is approved.": "आपका अनुरोध एडमिन को भेजा जाएगा। मंज़ूरी तक आपका खाता चालू रहेगा।",
  "Your request will be sent to our team for review. Your account will remain active until it is approved.": "आपका अनुरोध हमारी टीम को जाँच के लिए भेजा जाएगा। मंज़ूरी तक खाता चालू रहेगा।",
  "Your work, your earnings. We've got your back.": "आपका काम, आपकी कमाई। हम आपके साथ हैं।",
  "आपकी जानकारी Darji के साथ निजी और सुरक्षित रहती है।": "आपकी जानकारी दर्जी के साथ निजी और सुरक्षित रहती है।",
  "दर्जियों के लिए Darji कैसे काम करता है": "दर्जियों के लिए दर्जी ऐप कैसे काम करता है"
};
